name: Build & deploy

on:
  push:
    branches:
      - master
      - dev
	pull_request:
    branches:
      - main

jobs:
  build:
		name: Build
    runs-on: ubuntu-latest

    steps:
    # 步骤名称
   	- name: Checkout
        uses: actions/checkout@v4

		- name: Setup Node
			uses: actions/setup-node@v4
			with:
				node-version: 20.10.0
				cache: pnpm # 或 pnpm / yarn

    - name: Setup Pages
			uses: actions/configure-pages@v4
		- name: Install dependencies
      run: pnpm install

		- name: Build project
      run: pnpm build
    # 上传打包好的文件，所以下一步可以使用
		- name: Upload production-ready build files
      uses: actions/upload-artifact@v2
      with:
        name: production-files
        path: dist
	deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest

		steps:
    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: production-files
        path: dist

   	- name: Deploy to server
			uses: peaceiris/actions-gh-pages@v3
        with:
          branch: gh-pages
          folder: dist
          token: "${{ secrets.ACCESS_TOKEN  }}"