name: Desky
on:
  push:
    branches:
      - master
      - dev
concurrency:
  group: pages
  cancel-in-progress: false
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # 步骤名称
   	- name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # 如果未启用 lastUpdated，则不需要
		- name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm # 或 pnpm / yarn
    - name: Setup Pages
        uses: actions/configure-pages@v4
		- name: Install dependencies
		- name: Build project
      run: pnpm build
    # 上传打包好的文件，所以下一步可以使用
		- name: Upload production-ready build files
      uses: actions/upload-artifact@v2
      with:
        name: production-files
        path: dist
	deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
      steps:
    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: production-files
        path: dist
   	- name: Deploy to server
			uses: peaceiris/actions-gh-pages@v3
        with:
          branch: gh-pages
          folder: dist
          token: "${{ secrets.ACCESS_TOKEN  }}"